config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]
  resources :requests, only: %i[index]
  resources :profiles, only: %i[show edit update]
  resources :matchings
  resources :parties, only: %i[index] do
    get 'detail', on: :collection
  end
  resources :chat_rooms, only: %i[show] do
    resources :chat_messages, only: %i[create]
  end
  get 'blocks/confirm/:blocked_user_id', to: 'blocks#confirm', as: 'confirm_block'
  resources :blocks, only: %i[create destroy index]
  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
  end
  resources :password_resets, only: %i[new create edit update]
  resources :notifications, only: %i[index update] do
    collection do
      delete :mark_all_as_read
    end
  end
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  mount ActionCable.server => '/cable'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_before_login_header.html.erb
<header class="bg-info text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-between py-3">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <span class="fs-4 fst-italic ">FF14一緒に遊びませんか？</span>
      </a>
      <div class="col-md-7 text-end">
        <%= link_to 'ログイン', login_path, class: "btn btn-outline-light me-2" %>
        <%= link_to '登録', new_user_path, class: "btn btn-light" %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_footer.html.erb
<footer class="bg-info text-dark">
  <div class="container">
    <div class="row py-3 border-bottom">
      <div class="col d-flex justify-content-between">
        <span class="text-dark">© SQUARE ENIX</span> <!-- 追加されたテキスト -->
        <div>
          <%= link_to '利用規約', "https://kiyac.app/termsOfService/H4QwSwT7QFHxkJdoPaNA", class: 'ms-auto text-dark me-3' %> <!-- 左側のマージンを自動的に最大にする -->
          <%= link_to 'プライバシーボリシー', "https://kiyac.app/privacypolicy/RMeCH0KILayx8qzfwu1u", class: 'text-dark me-3' %>
          <%= link_to 'お問い合わせ', 'https://forms.gle/KKitrR5ToM7JDz5X9', class: 'text-dark' %> <!-- 最後のリンクにはマージンを適用しない -->
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-info text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-between py-3">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <span class="fs-4 fst-italic ">FF14一緒に遊びませんか？</span>
      </a>
      <div class="dropdown pr-3">
        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-bell"></i>
          <%= render 'notifications/notification_count' %>
        </button>
        <%= render 'shared/notification_dropdown' %>
      </div>
      <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag current_user.profile.avatar_url, size: '40x40', alt: 'mdo', class: 'rounded-circle' %>
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><%= link_to (t 'header.profile'), profile_path(current_user.profile), class: 'dropdown-item' %></li>
            <li><%= link_to (t 'defaults.status'), requests_path, class: 'dropdown-item' %></li>
            <li><%= link_to (t 'header.blocked_users'), blocks_path, class: 'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to (t 'defaults.logout'), logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %></li>
          </ul>
        </div>
    </div>
  </div>
</header>

app/views/shared/_notification_dropdown.html.erb
<ul class="dropdown-menu dropdown-menu-lg-end">
    <li class="dropdown-item">通知</li>
    <li><hr class="dropdown-divider"></li>
    <%= turbo_frame_tag 'notifications' do %>
        <% if @notifications.present? %>
                  <%= link_to '全てを既読する', mark_all_as_read_notifications_path,
                  class: 'btn btn-outline-dark btn-sm mx-auto',
                  method: :delete,
                  remote: true,
                  data: {turbo_method: :delete } %>
                  <% @notifications.each do |notification| %>
                      <%= render 'notifications/notification', { notification: notification } %>
                  <% end %>
        <% else %>
            <%= render 'notifications/no_notification' %>
        <% end %>
    <% end %>
</ul>