config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]
  resources :requests, only: %i[index]
  resources :profiles, only: %i[show edit update]
  resources :matchings
  resources :parties, only: %i[index] do
    get 'detail', on: :collection
  end
  resources :chat_rooms, only: %i[show] do
    resources :chat_messages, only: %i[create]
  end
  get 'blocks/confirm/:blocked_user_id', to: 'blocks#confirm', as: 'confirm_block'
  resources :blocks, only: %i[create destroy index]
  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
  end
  resources :password_resets, only: %i[new create edit update]
  resources :notifications, only: %i[index update] do
    collection do
      delete :mark_all_as_read
    end
  end
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  mount ActionCable.server => '/cable'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index; end
end

app/views/requests/index.html.erb
<%= content_for(:title, t('.title')) %>
<div class="cover-container d-flex w-75 p-3 mx-auto flex-column justify-content-center align-items-center" style= 'min-height: 85vh;'>
  <main class="px-3 text-center">
    <% if Matching.is_user_matched?(current_user.id) %>
      <h1 class="mb-4">あなたは今マッチング中です。</h1>
      <p class="lead">
        <%= link_to t('.party'), parties_path, class: 'btn btn-info btn-lg fw-bold border-white w-100', style: 'padding: .75rem 1.25rem; color: white;' %>
      </p>
    <% elsif current_user.matching.present? %>
      <h1 class="mb-4">あなたはマッチング待機中です。</h1>
      <p class="lead">
        <%= link_to t('.now_matching'), matching_path(current_user.matching), class: 'btn btn-info btn-lg fw-bold border-white w-100', style: 'padding: .75rem 1.25rem; color: white;' %>
      </p>
    <% else %>
      <h1 class="mb-4">あなたは今募集をしていません。</h1>
      <p class="lead">
        <%= link_to t('.new_matching'), new_matching_path, class: 'btn btn-info btn-lg fw-bold border-white w-100', style: 'padding: .75rem 1.25rem; color: white;' %>
      </p>
    <% end %>
    <p class="lead">
        <%= link_to t('.matching_table'), matchings_path, class: 'btn btn-success btn-lg fw-bold border-white w-100', style: 'padding: .75rem 1.25rem; color: white;' %>
      </p>
    <div class="mt-4">
      <%= link_to '使用方法はこちら', root_path, class: 'fs-4' %>
    </div>
  </main>
</div>